[package]
name = "quick_select"
version = "0.1.0"
edition = "2021"

[dependencies]
ordered-float = "4.6.0"
rand = "0.9.0-beta.1"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "quick_select_benchmark"
harness = false